### ISSUE TITLE
how make relation between two node

### ISSUE THREAD

**Issue by thantez** [dominique-vassard/ecto_neo4j#1]
hi
when I saw this repository, it makes me happy! thank you for this work.
how I can make a relation between two node with neo4j ecto driver and repo?
what should we do about relations? there is not any idea in document.
thank you.

**Comment by dominique-vassard** [comment]
Hi,
relationships are not supported because there's nothing close to this concepts in the relational ecto world.
It could be possible to rely on `belongs_to`, `has_one` ans `has_many` to know that there is a relationship between two types of nodes, and compute a relationship name from both node label. But first the name would not be relevant (remember that a graph is expressive) and second, the relationship types couldn't be managed.

To avoid the clumsiness of thinking a graph with relational concepts, an extension to the actual Ecto.schema is necessary in which relationships can be properly define.
And in fact, have an `Ecto.Query` which would be cypher-oriented rather than SQL_oriented.

EctoNeo4j eases the work on migration and for quik add / update / delete on a per node basis but can't go further because Ecto is realtional and sql oriented...
It's the first small step, I hope that someday I'll be able to provide / use something like this:
## Schema
```elixir
defmodule Person do
    use GraphSchema.Node

    node "Person" do
        property name, :string
        property born, :integer

        outgoing_relationship :directed, Movie
        outgoing_relationship :produced, Movie
        outgoing_relationship :wrote, Movie
        outgoing_relationship :follows, Person
        incoming_relationship :follows, Person
        outgoing_relationship :acted_in, Movie
        outgoing_relationship :reviewed, Movie

    end
end

defmodule Movie do
    use GraphSchema.Node
    
    node "Movie" do
        property title, :string
        property tagline, :string
        property release, :integer

        incoming_relationship :directed, Movie
        incoming_relationship :produced, Movie
        incoming_relationship :wrote, Movie
        incoming_relationship :acted_in, Movie
        incoming_relationship :reviewed, Movie
    end
end

defmodule Directed do
    use GraphSchema.Relationship

    relationship "DIRECTED" do
        start_node Person
        end_node Movie
    end
end

defmodule do
    use GraphSchema.Relationship

    relationship "PRODUCED" do
        start_node Person
        end_node Movie
    end
end

defmodule do
    use GraphSchema.Relationship

    relationship "WROTE" do
        start_node Person
        end_node Movie
        property wriiten_in, :date
    end
end

defmodule do
    use GraphSchema.Relationship

    relationship "FOLLOWS" do
        start_node Person
        end_node Person
    end
end

defmodule do
    use GraphSchema.Relationship

    relationship "ACTED_IN" do
        start Person
        end Movie

        property roles, :string
    end
end

defmodule do
    use GraphSchema.Relationship

    relationship "REVIEWED" do
        start Person
        end Movie
        
        property rating, :integer
        property summary, :string
    end
end
```

## Query
```elixir
query = match "Person" as p, 
        where: p.name == "Tom Hanks",
        return: p.name, p.born

query = match [
            "Person" as p,
            link_to: p, "DIRECTED" as rel, "Movie" as m
        ],
        return: p, rel, m

query = match [
    "Person" as p,
    path [
        p,
        link_to: p, "DIRECTED" as rel,  m
        "Movie" as
    ]
    with: path_length p,
    match: "Movie" m,
    where: release == p
    return: m
```

**Comment by thantez** [comment]
Yes, I hope too. It will be lovely. But I think if we want make relation between two node without schema, we can do it with build_assoc function.
for example
```
post = Repo.get(Post, 13)
comment = Repo.get(Comment, 2)

has_relation = %{
  lable: "has", 
  properties: %{
    date: "2019..."
  } 
} 

build_assoc(post, comment, has_relation)
```
Or better, `has_relation` be a schema
This is not like cql but is like ecto!

**Comment by pedronauck** [comment]
Sorry if I'm being rude, but I can't see why this package is useful if it doesn't support relationships. In fact, I tried a lot to build an application using this package, but I got stuck because of the relationships. It will be an honor for me to make a pull request in order to achieve the relationship feature, but I'm a very beginner in the Elixir/Neo4J world, so I think I couldn't help so much right now 😕

**Comment by dominique-vassard** [comment]
Hi @pedronauck, thanks for trying this package.
I  understand how frustrating it is to not be able to add relationship.
The fact is there is some difficulties transposing the relationship concept into Ecto relational language.
Also, keep in mind that if you can model your project and can translate your queries in SQL then you don't need Neo4j. Things as simple as `MATCH (Node)-[:Relationship*2..5]->(OtherNode)` (or just a simple path...) or queries using `WITH` are not translatable in SQL and have to be written in cypher.

Now, time to go further together, how should this project should be modelized and queried in Ecto terms without ambiguity?
 ![Blog Model](https://imgur.com/l95P8uo)
We can do it like this:
```elixir
defmodule MyApp.User do
  use Ecto.Schema
  @primary_key {:uuid, Ecto.UUID, []}

  schema "User" do
    field :first_name, :string
    field :last_name, :string

    has_many :posts, MyApp.Post
    many_to_many :followers, MyApp.User
    many_to_many :followed, MyApp.User
  end
end

defmodule MyApp.Post do
  use Ecto.Schema
  @primary_key {:uuid, Ecto.UUID, []}

  schema "Post" do
    field :title, :string
    field :text, :string

    belongs_to :author, MyApp.User
    has_many :comments, MyApp.Comment
    many_to_many :tags, MyApp.Comment
  end
end

defmodule MyApp.Comment do
  use Ecto.Schema
  @primary_key {:uuid, Ecto.UUID, []}

  schema "Comment" do
    field :text, :string

    belongs_to :author, MyApp.User
    belongs_to :post, MyApp.Post
  end
end

defmodule MyApp.Tag do
  use Ecto.Schema
  @primary_key {:uuid, Ecto.UUID, []}

  schema "Tag" do
    field :name, :string
    many_to_many :tagged_post, MyApp.Post
  end
end
```
But we have a problem here: `many_to_many` hides the relationship's direction...
At the creation / update stages, we can use `build_assoc` as suggested by @thantez but for the retrieval, it is impossible to know which direction should be used.
Additionally, someone looking at the schema can't understand how the model is.
`has_one`, `has_many` and `belongs_to` don't have such ambiguity then their use is straightforward.
Now what about the relationship's type and properties? Should we implement a schema for them? Add it as a special node's field / embedded_schema?

I think that relationship doesn't fit in Ecto: there is too many ambiguities or loss of specs.
For the node, we lose only the multiple label part.

EctoNeo4j is a first try to ease development with  Neo4j, and it works partially: you can use Ecto.Schema and manage your nodes easily, migrations works well (and are really useful), you can use multiple graph database easily and cypher query and cypher batch query are easy to launch.
But yes, it is far from being perfect.
As I mention earlier is this issue, the real way to have something very nice to work with would be:
- extending `Ecto.Schema` to have some `EctoNeo4j.GraphSchema` and `EctoNeo4j.GraphSchema` with `node` and `relationship` macros to model the projects
- dropping `Ecto.Query` in favour to some `EctoNeo4j.Cypher` to perform the query
Because Neo4j is NOT relational and cypher is NOT SQL.
I've started to work on this and I hope to have something working soon but it's not an easy task as I'm not a Elixir master! 

Sorry if this package is disappointing but it's a first (bad?) step to something great.

**Comment by pedronauck** [comment]
Yeah, I'm convinced of all your terms and indeed I think that Neo4J doesn't fit with the Ecto model. As I mentioned I'm starting to learning Elixir now and sometimes I saw a lot of things in Ecto that don't fit with other things, like GraphQL for example. With Neo4j I think that is the same, the entire mental model is different and tries to have something to fit both parts in the same way, in fact, it's not cool, a lot of Neo4j goodies will be lost in this process as you mentioned.

I like your proposal for the `EctoNeo4j.GraphSchema` and `EctoNeo4j.Cypher`, will be awesome to have this type of thing and will be a perfect way, mainly because we could enjoy all the good features of a graph database.

It will be nice to also think a good way to preload related nodes, because using `Bolt.Sips` to query using Cypher is easy but to aggregate, the results are something not so trivial. It's kinda annoying need to make `Enum` operations to get the results preloaded in the same node (eg. get all comments from a blog post)

But dude, really you don't owe me apologize. I'm very happy with your work and I don't contribute to him now because I think I don't have enough knowledge for this yet, but I know how hard is make open-source, create and maintain some project and I very glad that you take the first step. Count on me! I'm closely watching the project 🙌🏻

**Comment by jexp** [comment]
Just curious, would it make any sense to map relationships to a kind of "join" table in Ecto where the rel-type would be encoded in a column? `source, target, type, property1, property2`

Or even just a join-table-name per rel-type (which makes it less dynamic).
At least as a poor mans version?

**Comment by dominique-vassard** [comment]
I'll think about something to have a transition before the "big thing" which will take a while (along with a refactor of some parts of bolt_sips and bolt v4...).
I'll make a proposal as soon as I'm done with my move to countryside :)

**Comment by dominique-vassard** [comment]
Tell me what you think (or vote)!

# Proposal: Light Relationship Support

## Schema
### Define a schema
Relationship management will be built on the join-related Ecto function:  
    - `has_one`  
    - `has_many`  
    - `belongs_to`  
    - `many_to_many`  

foreign key concept is still irrelevant and won't be used.  
In order to define relationship, the node pointed by a relationship must have a specific field named `rel_type_of_relationship` (ex: `rel_wrote`).  
This field is a `:map` (for relationship properties) and has the option `virtual: true`  as it will not be persisted as is in the database.

Examples:  
Considering the following model:  
`(User {uuid: ..., ...})-[:WROTE {when: ...}]->(Post {uuid: ..., ...})`
schemas will be:

```elixir
defmodule MyApp.User do
  use Ecto.Schema
  @primary_key {:uuid, Ecto.UUID, []}

  schema "User" do
    field :first_name, :string
    field :last_name, :string

    has_many :posts, MyApp.Post
  end
end

defmodule MyApp.Post do
  use Ecto.Schema
  @primary_key {:uuid, Ecto.UUID, []}

  schema "Post" do
    field :title, :string
    field :text, :string
    field :rel_wrote, :map, virtual: true

    belongs_to :author, MyApp.User
  end
end
```

### Relationship direction
Relationship direction will be determined by the keyword used, expect for `many_to_many`.  
    - `has_one`: from current schema to the one specified in parameter
    - `has_many`: from current schema to the ones specified in parameter
    - `belongs_to`: from the schema specified in parameter to the current

## Querying
### Create
```elixir
user_data = %{
    first_name: "John",
    last_name: "Doe"
}
post_data = %{
    title: "First",
    text: "This is the first",
    rel_user: %{
    type: "WROTE",
    properties: %{
        when: ~D[2018-01-01]
    }
    }
}

user = User.changeset(%User{}, user_data)
# #Ecto.Changeset<
#   action: nil,
#   changes: %{first_name: "John", last_name: "Doe"},
#   errors: [],
#   data: #MyApp.User<>,
#   valid?: true
# >
post = Post.changeset(%Post{}, post_data)
# #Ecto.Changeset<
#   action: nil,
#   changes: %{text: "Very interesting", title: "First post", view: 2, rel_wrote: %{
#      when: ~D[2018-01-01]
#   }},
#   errors: [],
#   data: #MyApp.Post<>,
#   valid?: true
# >

user
|> Ecto.Changeset.put_assoc(:posts, [post])
|> Graph.Repo.insert()
# {:ok,
#   %MyApp.User{
#     __meta__: #Ecto.Schema.Metadata<:loaded, "User">,
#     first_name: "John",
#     id: 5,
#     inserted_at: ~N[2019-11-18 08:22:18],
#     last_name: "Doe",
#     posts: [
#       %MyApp.Post{
#         __meta__: #Ecto.Schema.Metadata<:loaded, "posts">,
#         author: #Ecto.Association.NotLoaded<association :author is not loaded>,
#         author_id: 5,
#         id: 1,
#         inserted_at: ~N[2019-11-18 08:22:18],
#         text: "Very interesting",
#         rel_wrote: %{
#            when: ~D[2018-01-01]
#         }
#         title: "First post",
#         updated_at: ~N[2019-11-18 08:22:18],
#       }
#     ],
#     updated_at: ~N[2019-11-18 08:22:18]
#   }}
```

The Cypher Equivalent would be:
```
CREATE (u:User {uuid: {uuid}, ...}),
CREATE (p:Post {uuid: {uuid}, ...})
MERGE (u)-[r:WROTE {when: "2018-01-01"}]->(p)
RETURN u, p, r
```
### Retrieve
It won't be possible to retrieve a relationship alone, the start node and the end node will be retrieved too.  
This is because there is no schema for relationship (yet).

```elixir
rel_data = %{type: "WROTE", properties: %{when: ~D[2018-01-01]}}
query = from u in User,
join: p in Post, on: p.rel_user == rel_data,
select: [u.first_name, u.last_name, p.title, p.text, p.rel_user]

GraphRepo.one(query)
# {:ok,
#   %MyApp.User{
#     __meta__: #Ecto.Schema.Metadata<:loaded, "User">,
#     first_name: "John",
#     id: 5,
#     inserted_at: ~N[2019-11-18 08:22:18],
#     last_name: "Doe",
#     posts: [
#       %MyApp.Post{
#         __meta__: #Ecto.Schema.Metadata<:loaded, "posts">,
#         author: #Ecto.Association.NotLoaded<association :author is not loaded>,
#         author_id: 5,
#         id: 1,
#         inserted_at: ~N[2019-11-18 08:22:18],
#         text: "Very interesting",
#         rel_wrote: %{
#            when: ~D[2018-01-01]
#         }
#         title: "First post",
#         updated_at: ~N[2019-11-18 08:22:18],
#       }
#     ],
#     updated_at: ~N[2019-11-18 08:22:18]
#   }}

```
will translate to:  
```
MATCH
  (u:User)-[rel:WROTE {when: "2018-01-01"}]->(p: Post)
RETURN
  u.first_name, u.last_name, p.title, p.text, rel
```
### Update
As creation, update is pretty straightforward:  
```elixir
user = GraphRepo.get(User, "valid-uuid", preload: :posts)
    
%User{posts: [post]} = user
new_rel = %{
    when: ~D[2000-01-01]
}
new_post = Post.changeset(post, %{rel_wrote: rel_wrote)

Ecto.Changeset.put_assoc(user, :posts, [post])
|> GraphRepo.update()
```
### Delete
There's two way to delete a relationship.
Either by managing the assoc:  
```elixir
user = GraphRepo.get(User, "valid-uuid", preload: :posts)
Ecto.Changeset.put_assoc(user, :posts, [])
|> GraphRepo.update()
```

Or through a query:  
```elixir
rel_data = %{when: ~D[2018-01-01]}
query = from u in User,
join: p in Post, on: p.rel_wrote == rel_data,
select: [u.first_name, u.last_name, p.title, p.text, p.rel_user]

GraphRepo.delete_all(query)
```

## The hard (unsolvable?) case of `many_to_many`
Considering the following schema:  
```elixir
defmodule MyApp.User do
  use Ecto.Schema
  @primary_key {:uuid, Ecto.UUID, []}

  schema "User" do
    field :first_name, :string
    field :last_name, :string
    field :rel_follows, :map, virtual: true

    many_to_many :followers, MyApp.User
    many_to_many :followed, MyApp.User
  end
end
```

At creation, relationship direction can be determined by the struct:  
```elixir
%User{
    first_name: "John",
    follows: [
        %User{
            first_name: "Jack",
            rel_follows: %{since: ~D[2017-06-09]}
        }
    ]
}
```
Here, the model is obviously: `(John)-[:FOLLOWS {since:...}]->(Jack)`  
But what a bout a query like this:  
```elixir
query = from u in User,
join: f in User, on: p.rel_follows == rel_data
```
Dow do we know the direction of `rel_follows`?  
Should we specifiy it in the name, like `rel_out_follows`?  
Something else?   


## Implement a custom type for relationship?
This could be an idea in order to define them easily, but will it be useful?

**Comment by dominique-vassard** [comment]
It was a hard work as `insert`, `update` and `preload` have been partially or entirely re-coded but I'm almost at the end!
The core feature is working, I "only" need to add typespecs, refactor some things and... write docs.
Expect a new ecto_neo4j version in few days or weeks.
For the moment, you can check how it works on this branch: https://github.com/dominique-vassard/ecto_neo4j/tree/light_relationship_support and especially in this test file: https://github.com/dominique-vassard/ecto_neo4j/blob/light_relationship_support/test/ecto_neo4j/relationships_test.exs

See you soon for the hex package update!

**Comment by dominique-vassard** [comment]
Ok, package is published. with a beautiful doc!
Some features are still lacking but I hope you'll enjoy what this new version provides.

Let me know what works and what don't
